In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
array = np.array(my_list)

In [5]:
array

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(4,2)

array([[0.60368714, 0.54582352],
       [0.2907016 , 0.78047756],
       [0.40589761, 0.97600533],
       [0.94115204, 0.67595089]])

In [18]:
np.random.rand(5)

array([0.51951591, 0.39788431, 0.94998809, 0.10223045, 0.02090842])

In [19]:
np.random.randn(3,4) #random numbers from standard normal distribution

array([[ 0.55686112, -0.92148671,  0.15289887, -0.50999817],
       [ 1.04360591,  0.28808748,  0.5582094 , -0.5094972 ],
       [-1.69280065, -1.48104576, -0.6572704 , -0.82304521]])

In [20]:
np.random.randint(1,100,10)

array([ 5,  4, 92, 14, 67, 84, 62, 77, 98, 43])

In [21]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranr = np.random.randint(0,50,10)
ranr

array([38, 37, 34, 44,  6, 36, 10, 26, 22, 40])

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranr

array([38, 37, 34, 44,  6, 36, 10, 26, 22, 40])

In [56]:
ranr.max()

44

In [58]:
ranr.min()

6

In [60]:
ranr.argmax()

3

In [62]:
ranr.argmin()

4

In [64]:
arr.shape

(25,)

In [70]:
b =arr.reshape(5,5)

In [72]:
b.shape

(5, 5)

In [74]:
b.dtype

dtype('int32')

In [78]:
from numpy.random import randint

In [80]:
randint(2,10)

4

In [82]:
### indexing and slicing

In [84]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[8]

8

In [88]:
arr[2:6]

array([2, 3, 4, 5])

In [90]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [92]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [94]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [96]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
slice_of_r = arr[0:6]
slice_of_r

array([0, 1, 2, 3, 4, 5])

In [100]:
slice_of_r[:] = 99
slice_of_r

array([99, 99, 99, 99, 99, 99])

In [102]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [104]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [106]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [108]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [110]:
## 2d array or matrix slicing

In [114]:
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [120]:
array_2d[0][0]

5

In [122]:
array_2d[0]

array([ 5, 10, 15])

In [124]:
array_2d[1][1]

25

In [126]:
array_2d[1,2]

30

In [130]:
array_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [132]:
## Conditional Selection

In [134]:
arr1= np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [140]:
bool_array = arr1 >5 

In [142]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [146]:
arr1[bool_array]

array([ 6,  7,  8,  9, 10])

In [148]:
arr1[arr1>4]

array([ 5,  6,  7,  8,  9, 10])

In [150]:
a_2d = np.arange(50).reshape(5,10)
a_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [152]:
a_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [160]:
## Numpy Operations

In [162]:
new_arr = np.arange(0,11)
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
new_arr + new_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [166]:
#same for subtraction and multiplication

In [168]:
new_arr + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [170]:
new_arr / new_arr ##0/0 is not possible in numpy

C:\Users\Vikrant Yadav\AppData\Local\Temp\ipykernel_33608\1627037830.py:1: RuntimeWarning: invalid value encountered in divide
  new_arr / new_arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [174]:
1 / new_arr # but the code will work with a warning

C:\Users\Vikrant Yadav\AppData\Local\Temp\ipykernel_33608\140994488.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / new_arr # but the code will work with a warning


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [176]:
new_arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [178]:
np.sqrt(new_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [180]:
np.exp(new_arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [182]:
new_arr.max()

10

In [184]:
np.max(new_arr)

10

In [186]:
np.sin(new_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [188]:
np.log(new_arr)

C:\Users\Vikrant Yadav\AppData\Local\Temp\ipykernel_33608\3293193979.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(new_arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [190]:
newly = np.arange(0,15)
add = np.arange(0,10)
newly+add

ValueError: operands could not be broadcast together with shapes (15,) (10,) 